version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db
  frontend:
    build: ./frontend/
    env_file: .env
    command: cp -r /app/build/. /app/result_build/
    volumes:
      - static:/app/result_build
  gateway:
    build: ./nginx/
    env_file: .env
    ports:
      - 9090:80
    volumes:
      - static:/static/
      - media:/media/
      - ./docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend
